-- MVUTO REAL ESTATE LTD — Seed current public listings
-- Run after schema.sql. Safe to re-run (upserts on slug).

INSERT INTO properties (
  slug, title, location, type, price, price_amount, size, image, gallery,
  status, featured, features, description, payment_plan, quick_info, published
) VALUES
(
  'chumani',
  'Chumani Project',
  'Kilifi County',
  'residential',
  '550,000',
  550000,
  'Plot',
  'https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Chumani_project_xbvsj7.jpg',
  '["https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Chumani_project_xbvsj7.jpg"]'::jsonb,
  'available',
  true,
  '["Prime land in Kilifi County","Flexible payment plan","Verified, legally compliant offering"]'::jsonb,
  'Prime land in a high-growth location. This offering is part of our verified, legally compliant portfolio with flexible payment plans to suit your investment goals.',
  '{"Deposit":"200,000","Installments":"12 monthly installments"}'::jsonb,
  '{"Deposit":"KES 200,000","Payment Plan":"12 monthly installments"}'::jsonb,
  true
),
(
  'mariakani-kaloleni',
  'Mariakani–Kaloleni',
  'Mariakani, Coast Region',
  'residential',
  '585,000',
  585000,
  'Plot',
  'https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Mariakani_-Kaloleni_dadglm.jpg',
  '["https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Mariakani_-Kaloleni_dadglm.jpg"]'::jsonb,
  'available',
  true,
  '["Mariakani–Kaloleni corridor","Flexible payment plan","Verified, legally compliant offering"]'::jsonb,
  'Prime land in a high-growth location. This offering is part of our verified, legally compliant portfolio with flexible payment plans to suit your investment goals.',
  '{"Deposit":"200,000","Installments":"12 monthly installments"}'::jsonb,
  '{"Deposit":"KES 200,000","Payment Plan":"12 monthly installments"}'::jsonb,
  true
),
(
  'mariakani-bypass',
  'Mariakani Bypass',
  'Mariakani, Coast Region',
  'residential',
  '350,000',
  350000,
  'Plot',
  'https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Mariakani_Bypass_qqjx8n.jpg',
  '["https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Mariakani_Bypass_qqjx8n.jpg"]'::jsonb,
  'available',
  true,
  '["Mariakani Bypass location","Flexible payment plan","Verified, legally compliant offering"]'::jsonb,
  'Prime land in a high-growth location. This offering is part of our verified, legally compliant portfolio with flexible payment plans to suit your investment goals.',
  '{"Deposit":"150,000","Installments":"12 monthly installments"}'::jsonb,
  '{"Deposit":"KES 150,000","Payment Plan":"12 monthly installments"}'::jsonb,
  true
),
(
  'diani',
  'Diani Project',
  'Diani, South Coast',
  'beach',
  '1.95M',
  1950000,
  'Plot',
  'https://res.cloudinary.com/dyfnobo9r/image/upload/v1773041195/Diani_project_nugmc5.jpg',
  '["https://res.cloudinary.com/dyfnobo9r/image/upload/v1773041195/Diani_project_nugmc5.jpg"]'::jsonb,
  'available',
  true,
  '["Diani, South Coast","Flexible payment plan","Verified, legally compliant offering"]'::jsonb,
  'Prime land in a high-growth location. This offering is part of our verified, legally compliant portfolio with flexible payment plans to suit your investment goals.',
  '{"Deposit":"700,000","Installments":"12 monthly installments"}'::jsonb,
  '{"Deposit":"KES 700,000","Payment Plan":"12 monthly installments"}'::jsonb,
  true
),
(
  'bofa',
  'Bofa Project',
  'Kilifi County',
  'beach',
  '1.85M',
  1850000,
  'Plot',
  'https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Bofa_Project_slgq2b.jpg',
  '["https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Bofa_Project_slgq2b.jpg"]'::jsonb,
  'available',
  false,
  '["Bofa, Kilifi County","Flexible payment plan","Verified, legally compliant offering"]'::jsonb,
  'Prime land in a high-growth location. This offering is part of our verified, legally compliant portfolio with flexible payment plans to suit your investment goals.',
  '{"Deposit":"700,000","Installments":"12 monthly installments"}'::jsonb,
  '{"Deposit":"KES 700,000","Payment Plan":"12 monthly installments"}'::jsonb,
  true
),
(
  'kibao-kiche',
  'Kibao Kiche',
  'Coast Region',
  'residential',
  '550,000',
  550000,
  'Plot',
  'https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Kibao_Kiche_eryng5.jpg',
  '["https://res.cloudinary.com/dyfnobo9r/image/upload/v1773038630/Kibao_Kiche_eryng5.jpg"]'::jsonb,
  'available',
  false,
  '["Kibao Kiche, Coast Region","Flexible payment plan","Verified, legally compliant offering"]'::jsonb,
  'Prime land in a high-growth location. This offering is part of our verified, legally compliant portfolio with flexible payment plans to suit your investment goals.',
  '{"Deposit":"200,000","Installments":"12 monthly installments"}'::jsonb,
  '{"Deposit":"KES 200,000","Payment Plan":"12 monthly installments"}'::jsonb,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  location = EXCLUDED.location,
  type = EXCLUDED.type,
  price = EXCLUDED.price,
  price_amount = EXCLUDED.price_amount,
  size = EXCLUDED.size,
  image = EXCLUDED.image,
  gallery = EXCLUDED.gallery,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  features = EXCLUDED.features,
  description = EXCLUDED.description,
  payment_plan = EXCLUDED.payment_plan,
  quick_info = EXCLUDED.quick_info,
  published = EXCLUDED.published,
  updated_at = NOW();
